# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import problem2.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=problem2.models.file_name)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('checksum', models.CharField(max_length=256)),
            ],
        ),
    ]
