# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='checksum',
            new_name='checksum_md5',
        ),
        migrations.AddField(
            model_name='file',
            name='checksum_sha256',
            field=models.CharField(max_length=256),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='file',
            table='problem2_file',
        ),
    ]
